[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "webpyx"
version = "3.0.1"
description = "Python utility library for target validation and port parsing"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"

authors = [
    { name = "Pugazhenthi J", email = "pugazhenthij283@gmail.com" }
]

keywords = [
    "python",
    "cybersecurity",
    "validator",
    "network",
    "recon"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]