[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "webpyslib"
version = "1.0.0"
description = "Python utility library for cybersecurity"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
    { name = "Pugazhenthi J", email = "pugazhenthij283@gmail.com" }
]

keywords = [
    "python",
    "cybersecurity",
    "network",
    "validator",
    "recon"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent"
]

dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]